export { default as Account } from "./moverAccount";
export { default as Dashboard } from "./moverDashboard";
export { default as Typography } from "./moverTypography";
export { default as Orders } from "./moverOrders/moverindex";
export { default as Deliveries } from "./moverDeliveries";
export { default as Vehical } from "./moverVehical";
export { default as NotFound } from "./moverNotFound";
export { default as ProductList } from "./moverProductList";
export { default as Settings } from "./moverSettings";
export { default as SignIn } from "./moverSignIn";
export { default as SignUp } from "./moverSignUp";
export { default as FormPasswordReset } from "./moverFormPasswordReset";
export { default as MoverResidential } from "./MoverResidential";
export { default as StoreList } from "./moverMovers";
export {default as Category} from "./Category";
export { default as MoverCommercial } from "./MoverCommercial";
