const CompanyNameList=[
  'State Farm Insurance',
  'Company Not Listed',
  'American Spirit Insurance',
  	'American Skyline Insurance Company',	
  	'American Service Insurance',	
  	'American Republic',	
  	'American Reliable Ins Co',	
  	'American Protection Insurance',
  	'American National Insurance',
  	'American Motorists Insurance',	
  	'American Manufacturers',
  	'American International South',
  	'American International Pacific',
  	'American International Ins',
  	'American Insurance',
	'American Home Assurance',
  	'American Financial',
  	'American Family Insurance',
  	'American Empire Insurance',
  	'American Economy Ins Co',
  	'American Direct Business Insurance',
  	'American Casualty',
  	'American Automobile',
  	'American Alliance Ins Co',	
  	'Amco Ins Co	Amco Ins Co',
  	'Allstate Insurance',
  'Allied',
  	'Alfa',
  	'AIU Insurance',
  	'AIG',
  	'AAA Insurance Co.',
  	'21st Century Insurance'	,
  	'American Standard Insurance - OH',	
  	'American Standard Insurance - WI',
  	'Amex Assurance Co',
  	'Amica Insurance',
  	'Associated Indemnity',
  	'Atlanta Casualty',
  	'Atlantic Indemnity',
  	'Auto Club Insurance Company',
  	'Brooke Insurance',
  	'Cal Farm Insurance',
  	'California Automobile Ins Co',
  	'California Casualty and Fire Ins Co',
  	'California State Auto Assoc',
  	'Century National Ins',
  	'Chubb Group of Ins Co',
  	'Clarendon National Insurance',
  	'CNA',
  	'Colonial Penn',
  	'Commerce West',
  	'Commercial Union',
  	'Continental Casualty',
  	'Continental Divide Insurance',
  	'Continental Insurance'	,
  	'Cotton States Insurance',
  	'Country Financial',
  	'Countrywide Insurance',
  	'Dairyland Insurance',
  	'Eagle Ins Co',
  	'Electric Insurance',
  	'Empire Fire and Marine',
  	'Erie Insurance Company',
  	'Esurance',
  	'Explorer',
  	'Farm Bureau/Farm Family/Rural'	,
  	'Farmers Insurance',
  	'Farmers Union'	,
  	'Federal Ins Co',
  	'Financial Indemnity',
  	'Fire and Casualty Insurance Co of CT',
  	"Fireman's Fund",
  	'Geico Casualty',
  	'General Accident Insurance'	,
  	'GMAC Insurance'	,
  	'Great American Ins Co',
  	'Guaranty National Insurance',
  	'Guide One Insurance',
  	"Hanover Lloyd's Insurance Company",
  	"Hartford Accident and Indemnity",
  	'High Point Insurance',
  	'IFA Auto Insurance',
  	'Infinity Insurance',
  	'Integon',
  	'Insurance Co of the West',
  	'Kemper Insurance',
  	'Leader National',
  	'Liberty Insurance Corp'	,
  	'Liberty Mutual Insurance',
  	'Liberty Northwest Insurance',
  	'Lumbermens Mutual',
  	'Maryland Casualty',
  	'Mercury',
  	'MetLife Auto and Home',
  	'Mid Century Insurance',
  	'Mid-Continent Casualty',
  	'Middlesex Insurance',
  	'Mutual of Omaha',
  	'National Ben Franklin Insurance',
  	'National Casualty',
  	'National Continental Insurance',
  	'National Fire Insurance Company of Hartford',
  	'National Union Fire Insurance of LA',
  	'National Union Fire Insurance of PA',
  	'Nationwide General Insurance',
  	'Northwestern Pacific Indemnity',
  	'NJ Skylands Insurance',
  	'Ohio Casualty',
  	'Omni Insurance',
  	'Orion Auto Ins Co',
  	'Pacific Indemnity',
  	'Pacific Insurance',
  	'Patriot General Insurance',
  	'Peak Property and Casualty Insurance',
  	'PEMCO Insurance',
  	'Progressive',
  	'Prudential Insurance Co.',
  	'Republic Indemnity',
  	'Response Insurance',
  	'SAFECO',
  	'Safeway Insurance',
  	'Selective InsGroup',
  	'Sentinel Insurance',
  	'Sentry Insurance Group',
  	'Shelter Insurance Co.',
  	'St. Paul',
  	'Standard Fire Insurance Company',
  	'State and County Mutual Fire Insurance',
  	'State Auto Ins Co',
  	'State Farm County',
  	'State National Insurance',
  	'Superior Guaranty Insurance',
  	'Superior Insurance',
  	'TICO Insurance',
  	'TIG Insurance Group',
    'Titan',
  	'Travelers Insurance Company',
  	'Tri-State Consumer Insurance',
  	'Unigard Ins',
  	'United Services Automobile Association',
  	'Unitrin Direct',	
  	'USAA',	
  	'USF and G',	
  	'Wawanesa Mutual',
  	'Zurich Ins Group',
  	'Not Currently Insured'	
];

export default CompanyNameList;
